### ISSUE TITLE
ami-22b7ff48 missing

### ISSUE THREAD

**Issue by djpain** [dcao96/pi-stream#1]
I was looking for this ami today and it seems it's been removed. Do you want me to create a pull request updating the readme.md ? or I can create a new ami 👍

**Comment by gmosley** [comment]
Unfortunately we haven't been maintaining this repo and the old ami has been deleted. The steps [here](https://github.com/david-cao/pi-stream/blob/master/AWSsetup.md) might work.

We are planning to revive the project and possibly switch to the NVIDIA GRID/Capture API which would work with both AWS g2 series and Azure NV series.

If you create a new ami, feel free to create a pull request.

**Comment by djpain** [comment]
awesome! I'll submit one once i get around to it.
